openapi: 3.0.3
info:
  title: Users Aggregator API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get merged users from all data sources
      operationId: listUsers
      tags: [Users]
      responses:
        '200':
          description: Aggregated list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required: [id, username, name, surname]
      properties:
        id:
          type: string
          example: example-user-id-1
        username:
          type: string
          example: user-1
        name:
          type: string
          example: User
        surname:
          type: string
          example: Userenko